# Generated by Django 4.0.6 on 2023-04-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GotOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=150)),
                ('order_date', models.DateField()),
                ('got_qty', models.IntegerField()),
                ('remaining_qty', models.IntegerField()),
                ('distributed_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DistributedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrubuted_to', models.CharField(max_length=150)),
                ('distributed_qty', models.IntegerField()),
                ('got_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.gotorder')),
            ],
        ),
    ]
