# Generated by Django 4.0.6 on 2023-04-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributedorder',
            name='completed_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gotorder',
            name='distributed_qty',
            field=models.IntegerField(default=0),
        ),
    ]
