# Generated by Django 4.0.6 on 2023-04-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_distributedorder_completed_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gotorder',
            name='remaining_qty',
        ),
    ]
