# Generated by Django 4.0.6 on 2023-04-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_gotorder_remaining_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributedorder',
            old_name='distrubuted_to',
            new_name='distributed_to',
        ),
    ]
