# Generated by Django 4.0.6 on 2023-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_distrubuted_to_distributedorder_distributed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributedorder',
            name='distributed_date',
            field=models.DateField(default='2023-1-1'),
            preserve_default=False,
        ),
    ]
