# Generated by Django 4.0.6 on 2023-04-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_distributedorder_distributed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='gotorder',
            name='delivery_qty',
            field=models.IntegerField(default=0),
        ),
    ]
