# Generated by Django 4.0.6 on 2023-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_distributedorder_distributed_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gotorder',
            old_name='delivery_qty',
            new_name='completed_qty',
        ),
        migrations.AddField(
            model_name='distributedorder',
            name='damage_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distributedorder',
            name='return_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gotorder',
            name='damage_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gotorder',
            name='return_qty',
            field=models.IntegerField(default=0),
        ),
    ]
