# Generated by Django 4.2.6 on 2023-10-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_delivery_qty_gotorder_completed_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gotorder',
            name='completed_qty',
        ),
        migrations.RemoveField(
            model_name='gotorder',
            name='damage_qty',
        ),
        migrations.RemoveField(
            model_name='gotorder',
            name='distributed_qty',
        ),
        migrations.RemoveField(
            model_name='gotorder',
            name='return_qty',
        ),
    ]
