# Generated by Django 4.2.6 on 2023-10-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_gotorder_completed_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributedorder',
            name='complete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gotorder',
            name='complete_status',
            field=models.BooleanField(default=False),
        ),
    ]
