# Generated by Django 4.2.6 on 2023-11-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('order', '0010_distributedorder_complete_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gotorder',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),
    ]
